#version of Docker compose file
version: "3.9"

services:
  app:
    build:
      # use current directry
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
    #maping working directry we change or update in local project it update alkso in the docker container
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
